import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { documentId } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

    const { data: doc, error } = await supabase.from("documents").select("*").eq("id", documentId).single();
    if (error || !doc) throw new Error("Document not found");

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content: `You are a legal case summary generator. Generate a professional, concise case summary suitable for court or legal review. Return ONLY valid JSON:
{
  "summary": "<3-4 sentence professional summary>",
  "keyFindings": ["<finding 1>", "<finding 2>", ...],
  "legalImplications": "<brief legal implications>",
  "recommendedActions": ["<action 1>", "<action 2>", ...],
  "tags": ["<auto-generated tag 1>", "<tag 2>", ...]
}`,
          },
          {
            role: "user",
            content: `Document: ${doc.file_name}
Type: ${doc.case_type}
Status: ${doc.status}
Risk Score: ${doc.risk_score}/100
Risk Level: ${doc.risk_level}
Confidence: ${doc.confidence}%
Clauses: ${JSON.stringify(doc.clauses)}
Risks: ${JSON.stringify(doc.risks)}
Alerts: ${JSON.stringify(doc.alerts)}
Recommendation: ${JSON.stringify(doc.recommendation)}`,
          },
        ],
      }),
    });

    if (!response.ok) {
      if (response.status === 429) return new Response(JSON.stringify({ error: "Rate limited" }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      if (response.status === 402) return new Response(JSON.stringify({ error: "Credits exhausted" }), { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      throw new Error("AI failed");
    }

    const aiData = await response.json();
    const content = aiData.choices?.[0]?.message?.content || "";
    let result;
    try {
      const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/) || [null, content];
      result = JSON.parse(jsonMatch[1]!.trim());
    } catch {
      throw new Error("Failed to parse summary");
    }

    // Save summary and tags back to document
    await supabase.from("documents").update({
      summary: result.summary,
      tags: result.tags || [],
    }).eq("id", documentId);

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-summary error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
